### PR TITLE
Create PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by babusid**
copied bps pr template over

### CODE REVIEW

**Comment by babusid** [comment]
@IshDeshpa @Cam0Cow pls merge 🙏🙏🧎🏾‍♂️

**Comment by Cam0Cow** [comment]
There's definitely some edits we need to make first.

**Comment by IshDeshpa** [comment]
See https://github.com/lhr-solar/Embedded-Sharepoint/issues/23. Move this to the sharepoint and add an issue template.

**Comment by babusid** [comment]
> See https://github.com/lhr-solar/Embedded-Sharepoint/issues/23. Move this to the sharepoint and add an issue template.

Can we even have them in the sharepoint and still have GH pick it up as a template, I thought it had to be in the root dir

**Pull request closed without merging**
