### PR TITLE
Script to make simulator launch easier

### PR DESCRIPTION
**Pull request by rafidh611**

### CODE REVIEW

**Review by JimothyGreene — CHANGES_REQUESTED** [review]
Can you rename the file to just be called `simulate`? That way we just have to run `./simulate` to run it.

**Review by JimothyGreene — CHANGES_REQUESTED** [review]
Working well. You can delete the simulate.py symbolic link that's in the root Controls folder as part of this PR as well. Since that's no longer needed.

**Review by JimothyGreene — APPROVED** [review]
Looking good and works well for me

**Review by ErickCortez98 — APPROVED** [review]
Working well for me. 
Note: I got issues when trying to run it under the WSL directory, after changing the Controls directory to Windows the script worked.

**Pull request merged**
