### PR TITLE
Integrated Driver Testfile

### PR DESCRIPTION
**Pull request by babusid**
Tests all drivers in their current state in one test file.

### CODE REVIEW

**Review by JimothyGreene — CHANGES_REQUESTED** [review]
This should ideally run in some sort of infinite loop so it can just run while we test things on the simulator UI and interactions between drivers.

**Review by JimothyGreene — CHANGES_REQUESTED** [review]
Looks like it's working pretty well. Just try to format the output a bit nicer. Some more spacing so that the title of the column lines up with its data.

**Review by ErickCortez98 — CHANGES_REQUESTED** [review]
Seems to be working great, but it would maybe be useful to print out some comments specifying which module is being tested at each part of the process as well as maybe which part in the GUI can be used to modify or visualize the outputs

**Review by JimothyGreene — APPROVED** [review]
Works well for me now. I think we'll be integrating this one into `master`

**Review by Cam0Cow — APPROVED** [review]

**Pull request merged**
