### PR TITLE
Fix issue with uCOS and a few other things.

### PR DESCRIPTION
**Pull request by chaseblock**

### CODE REVIEW

**Review by JimothyGreene — APPROVED** [review]
@chaseblock always able to solve the issue. Not sure how you knew this was the issue, but I'm glad you're a genius lol.

**Review by babusid — APPROVED** [review]
@chaseblock how did you even figure this out

**Comment by ClarkPoon** [comment]
@JimothyGreene @babusid There's a register that gets set when there's a hard fault that tells you what caused the hard fault.

**Comment by babusid** [comment]
> @JimothyGreene @babusid There's a register that gets set when there's a hard fault that tells you what caused the hard fault.

What register is it? Just for future reference if we hit any other hard faults

**Comment by ClarkPoon** [comment]
> > @JimothyGreene @babusid There's a register that gets set when there's a hard fault that tells you what caused the hard fault.
> 
> What register is it? Just for future reference if we hit any other hard faults

I think it is the CFSR register, which I found described in [this article](https://interrupt.memfault.com/blog/cortex-m-fault-debug)

**Pull request merged**
